### ISSUE TITLE
TypeError: ... .epliogue is not a function

### ISSUE THREAD

**Issue by sunyuding** [codecapers/alpha-vantage-cli#1]
After I installed the Cli, I run alpha-vantage-cli -v to check and an error occured.

alpha-vantage-cli/build/cli.js:92
    .epliogue("Getting your API key:\r\n" +
     ^

TypeError: yargs.usage(...).example(...).help(...).alias(...).option(...).option(...).option(...).option(...).option(...).option(...).option(...).demandOption(...).help(...).epliogue is not a function
    at Object.<anonymous> (/Library/WebServer/Documents/Homeworks/8/node_modules/alpha-vantage-cli/build/cli.js:92:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Comment by Balinus** [comment]
Same error here.

**Comment by ashleydavis** [comment]
Fixed now
